### ISSUE TITLE
machine resource does not re-create terminated AWS instances

### ISSUE THREAD

**Issue by scarolan** [chef-boneyard/chef-provisioning#261]
It appears that when an instance is terminated, Chef Provisioning simply waits for it to become available, instead of checking the state and recreating the instance.

**Comment by jkeiser** [comment]
Pretty sure this was fixed by PR #40 in around the same timeframe.

@lynchc says the chef-provisioning-aws driver is now checking for :terminated but not `:archived` state, which could cause some bugs--let's leave this open and confirm.
