### ISSUE TITLE
bootstrap_options are a Hash with symbols as keys

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-provisioning#304]
When using node attributes to pass into `with_machine_options`,
conditional tests that check, for example whether the bootstrap
options contains a key name, we have logic like this

Conditional checks in chef-provisioning use symbols as the hash keys.
This means that users cannot be assured that passing in the hash as a
node attribute in a recipe will get what they expect. For example,
chef-provisioning-aws has this conditional:

``` ruby
!bootstrap_options[:key_name]
```

However, if I set my bootstrap_options as an attribute like this:

``` ruby
default['driver']['machine_options'] = {
                      :ssh_username => 'ubuntu',
                      :use_private_ip_for_ssh => false,
                      :bootstrap_options => {
                                             :key_name => 'hc-metal-provisioner',
                                             :image_id => 'ami-b99ed989',
                                             :flavor_id => 'm3.medium'
                                            }
                    }

```

While `:key_name` is specified as a symbol, Chef actually turns this
into a string since it's an attribute.

I can work around this by converting the attribute to a hash and then
walking the hash to convert all strings to symbols, but it would be
preferable that I can just shove my attributes into
`with_machine_options` and it does the magic thing to work :).

**Comment by tyler-ball** [comment]
I talked with @jkeiser about this - we want to stop transforming objects that are passed as machine_options, bootstrap_options, etc.  Right now we call `.to_hash` on those options (I think from [here](https://github.com/chef/cheffish/blob/ac3248e9b14e6275882a167ebcace6c7b0d8b870/lib/cheffish/chef_provider_base.rb#L59-L69)) which loses the ability to reference the attribute mash correctly.  But because there is a workaround for this we are going to hold off until after the 1.0 release.

**Comment by jtimberman** [comment]
Any further consideration of this?

**Comment by jkeiser** [comment]
It does seem important: we should be able to accept node attributes with hash values in machine_options. @tyler-ball

**Comment by szymonpk** [comment]
Any updates on this? Maybe I can help somehow? I would like to love to use Mash as machine_options or at least I would like to avoid converting node attributes to hash.
