### ISSUE TITLE
Support policyfiles to replace run lists

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-provisioning#407]
Machine resources should support adding configuration and using Policyfiles in the place of run lists.

To support policyfiles _now_, one has to inject `chef_config` like this:

``` ruby
machine 'bootstrap-backend' do
  chef_config "use_policyfile true\nversioned_cookbooks true\npolicy_group 'reference'\npolicy_name 'bootstrap-backend'"
end
```

This works, however it would be nice to do this instead:

``` ruby
machine 'bootstrap-backend' do
  policy_name 'bootstrap-backend'
  policy_group 'reference'
end
```

The code would then detect that it should use policyfile configuration, and ask the Chef Server it is configured to talk to about whether it supports the policyfile API end point, or if it should use compatibility mode. If the API supports policyfile end point, the following would be appended to the `client.rb`:

``` ruby
use_policyfile true
policy_document_native_api true

policy_group "#{policy_group}"
policy_name "#{policy_name}"
```

If the API doesn't support the API, then fall back to compatibility mode:

``` ruby
use_policyfile true
policy_document_native_api false
deployment_group "#{policy_name}-#{policy_group}"
```

**Comment by double-z** [comment]
hey @jtimberman i actually put in a PR doing exactly this as far as the resource attributes - #404 .

it doesn't have the detection features you describe above though; gonna look into adding that though, that's a good idea.

**Comment by jtimberman** [comment]
@double-z Cool, I left a comment on #404 :cake:.
