### ISSUE TITLE
Closed network issue

### ISSUE THREAD

**Issue by paveljeloudovski** [chef-boneyard/chef-provisioning#529]
Ohai, 
I'm working in an environment with no internet connection
Doing :allocate and :ready for machines works 100%.

However it fails when trying to do a :setup action.

The part where it creates and copies the client.pem and client.rb to the provisioned node succeeds.
Despite providing the [:convergence_options][:install_sh_url] with a value of a local install script url,
the run fails because it's trying to download the package from chef.io. 

Any Ideas on how to force using a local URL for the package installation?

Thanks in advance.

**Comment by deniskin82** [comment]
Just come up with your own custom install bash script to basically download a chef package(rpm, deb) from a HTTP based server within your local network.
Or
1. by using `machine_file` resource to upload a RPM/DEB package to the provisioned node from your local path
2. then use `machine_execute` resource to install that uploaded package on the provisioned node
